// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissionIT.WebHelp.Data;

namespace MissionIT.WebHelp.Migrations
{
    [DbContext(typeof(HelpDbContext))]
    [Migration("20180628154217_SeedingSectionAndArticle")]
    partial class SeedingSectionAndArticle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MissionIT.WebHelp.Models.Article", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArticleDescription")
                        .IsRequired()
                        .HasMaxLength(10000);

                    b.Property<string>("ArticleImageUrl")
                        .IsRequired();

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("SectionID");

                    b.HasKey("ArticleID");

                    b.HasIndex("SectionID");

                    b.ToTable("tblArticles");

                    b.HasData(
                        new { ArticleID = 1, ArticleDescription = "werwwwwwwwwwwwwwwwwwwwwwwwwewrwerwerwerwe", ArticleImageUrl = "010001.jpg", ArticleName = "Menu", SectionID = 1 },
                        new { ArticleID = 2, ArticleDescription = "werwwwwwwwwwwwwwwwwwwwwwwwwewrwerwerwerwe", ArticleImageUrl = "010002.jpg", ArticleName = "Routes", SectionID = 2 },
                        new { ArticleID = 3, ArticleDescription = "werwwwwwwwwwwwwwwwwwwwwwwwwewrwerwerwerwe", ArticleImageUrl = "010003.jpg", ArticleName = "Drivers", SectionID = 2 },
                        new { ArticleID = 4, ArticleDescription = "wssssssssssssssssssssssssssssssssssss", ArticleImageUrl = "020004.jpg", ArticleName = "Vehicles", SectionID = 3 },
                        new { ArticleID = 5, ArticleDescription = "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", ArticleImageUrl = "020005.jpg", ArticleName = "Drivers", SectionID = 3 },
                        new { ArticleID = 6, ArticleDescription = "werwwwwwwwwwwwwwwwwwwwwwwwwewrwerwerwerwe", ArticleImageUrl = "050006.jpg", ArticleName = "Audit Trial", SectionID = 4 }
                    );
                });

            modelBuilder.Entity("MissionIT.WebHelp.Models.Section", b =>
                {
                    b.Property<int>("SectionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("SectionID");

                    b.ToTable("tblSections");

                    b.HasData(
                        new { SectionID = 1, SectionName = "Introduction" },
                        new { SectionID = 2, SectionName = "Time Line" },
                        new { SectionID = 3, SectionName = "Customer Service" },
                        new { SectionID = 4, SectionName = "My Favourites" },
                        new { SectionID = 5, SectionName = "User Diary" },
                        new { SectionID = 6, SectionName = "Audit Trial" },
                        new { SectionID = 7, SectionName = "Quick Change" },
                        new { SectionID = 8, SectionName = "Jobs" },
                        new { SectionID = 9, SectionName = "Add New" },
                        new { SectionID = 10, SectionName = "Lists" },
                        new { SectionID = 11, SectionName = "Venue" },
                        new { SectionID = 12, SectionName = "Route" },
                        new { SectionID = 13, SectionName = "Exception" },
                        new { SectionID = 14, SectionName = "Passenger" },
                        new { SectionID = 15, SectionName = "Driver" },
                        new { SectionID = 16, SectionName = "Attendent" },
                        new { SectionID = 17, SectionName = "Vehicle" },
                        new { SectionID = 18, SectionName = "Provider" },
                        new { SectionID = 19, SectionName = "Work Shop" },
                        new { SectionID = 20, SectionName = "Scheduling" },
                        new { SectionID = 21, SectionName = "All DBS Application" },
                        new { SectionID = 22, SectionName = "Messaging" },
                        new { SectionID = 23, SectionName = "Accounts" },
                        new { SectionID = 24, SectionName = "Documents" },
                        new { SectionID = 25, SectionName = "Utilities" },
                        new { SectionID = 26, SectionName = "How to use Help" }
                    );
                });

            modelBuilder.Entity("MissionIT.WebHelp.Models.Article", b =>
                {
                    b.HasOne("MissionIT.WebHelp.Models.Section", "Section")
                        .WithMany("Articles")
                        .HasForeignKey("SectionID");
                });
#pragma warning restore 612, 618
        }
    }
}
