// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MissionIT.WebHelp.Data;
using System;

namespace MissionIT.WebHelp.Migrations
{
    [DbContext(typeof(HelpDbContext))]
    [Migration("20180628151606_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MissionIT.WebHelp.Models.Article", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArticleDescription")
                        .IsRequired()
                        .HasMaxLength(10000);

                    b.Property<string>("ArticleImageUrl")
                        .IsRequired();

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("SectionID");

                    b.HasKey("ArticleID");

                    b.HasIndex("SectionID");

                    b.ToTable("tblArticles");
                });

            modelBuilder.Entity("MissionIT.WebHelp.Models.Section", b =>
                {
                    b.Property<int>("SectionID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("SectionID");

                    b.ToTable("tblSections");
                });

            modelBuilder.Entity("MissionIT.WebHelp.Models.Article", b =>
                {
                    b.HasOne("MissionIT.WebHelp.Models.Section", "Section")
                        .WithMany("Articles")
                        .HasForeignKey("SectionID");
                });
#pragma warning restore 612, 618
        }
    }
}
